# Generated by Django 4.0.6 on 2022-07-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[(1, 'A1'), (2, 'A2')], max_length=10, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
