# Generated by Django 4.0.6 on 2022-07-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(choices=[('1', 'A1'), ('2', 'A2'), ('3', 'B1')], max_length=10),
        ),
    ]
