# Generated by Django 4.0.6 on 2022-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avaiable',
            field=models.BooleanField(default=True),
        ),
    ]
