# Generated by Django 4.0.6 on 2022-07-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0, verbose_name='Days')),
                ('state', models.CharField(choices=[(1, 'Pendiente'), (2, 'Pagado'), (3, 'Eliminado')], default='Pendiente', max_length=50, verbose_name='State')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('method', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
