# Generated by Django 4.0.6 on 2022-07-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CI',
            field=models.CharField(max_length=50, unique=True, verbose_name='Carnet de Identidad'),
        ),
    ]
